### ISSUE TITLE
Work is based on point-based questions

### ISSUE THREAD

**Issue by Recialhot** [UPC-ViRVIG/SparsePoser#1]
Hello, I would like to know that the work is based on 6 points, but I look at the website demo and it seems that root is not available, that is, can it be trained and applied through 5 points? (VR headset, 2 controllers and 2 feet)

**Comment by JLPM22** [comment]
Hi! Thank you for reaching out! :)

Actually, our method does not predict the position of the root end-effector. Instead, we fix the position of the root joint to the root end-effector to have accurate global positioning, and then let SparsePoser adjust the full-body pose to align the other 5 tracking points. That's why, in the website demo, it looks like the root is not available. But it is actually an important part of the method. Thus, we need the 6 points to run the method. We are experimenting with removing additional tracking points in future projects.
