### ISSUE TITLE
Could you share the evaluate code for AMASS?

### ISSUE THREAD

**Issue by Lucifer-G0** [UPC-ViRVIG/SparsePoser#7]
I am considering using your model as a baseline for my research, but I have encountered difficulties in replicating the performance of your model on the AMASS dataset. Despite several attempts, I have not been able to achieve the results reported in the paper. Could you please provide the relevant code?

**Comment by JLPM22** [comment]
I think the problem you are encountering is with the preprocessing of AMASS. 

AMASS has a large variability in the rest poses for different users/motion. First, you should retarget all motion to a common skeleton with a well-defined rest pose (length of each bone can vary). Then train SparsePoser with that (you can use only the DanceDB for training as stated in the paper). We did that in the paper for the baselines and our method.

Unfortunately, I cannot share with you the code for retargeting because we used a third-party tool. But any tool should work. 

The evaluation code for positional error can be found in this repository. The jittery error I think I have pointed to the code I used in another issue. The rotational error I could share it with you later, I will have to search it (in any case the formula used is in the paper).

**Comment by Lucifer-G0** [comment]
Thank you for your assistance. I will review my code and retrain your model using DanceDB.

Regarding one final inquiry: Is your evaluation script configured to aggregate the results from 64-frame windows to determine the final outcome, or does it process the entire file as a single dataset for assessment, similar to how 'eval.py' operates?

**Comment by JLPM22** [comment]
For the evaluations in the paper we aggregate the results from 64-frame windows to simulate an online execution
